#ifndef ACNET_SOCKET_TAGS_H
#define ACNET_SOCKET_TAGS_H
#include <utility/tagitem.h>
#define ACSBTF_REF 0x8000U
#define ACSBTF_SET 0x0001U
#define ACSBTS_CODE 0x3FFFU
#define ACSBTM_CODE(tag) ((((UWORD)(tag)) >> 1) & ACSBTS_CODE)
#define ACSBTC_BREAKMASK 1
#define ACSBTC_SIGIOMASK 2
#define ACSBTC_SIGURGMASK 3
#define ACSBTC_SIGEVENTMASK 4
#define ACSBTC_ERRNO 6
#define ACSBTC_HERRNO 7
#define ACSBTC_DTABLESIZE 8
#define ACSBTC_FDCALLBACK 9
#define ACSBTC_LOGSTAT 10
#define ACSBTC_LOGTAGPTR 11
#define ACSBTC_LOGFACILITY 12
#define ACSBTC_LOGMASK 13
#define ACSBTC_ERRNOSTRPTR 14
#define ACSBTC_HERRNOSTRPTR 15
#define ACSBTC_IOERRNOSTRPTR 16
#define ACSBTC_S2ERRNOSTRPTR 17
#define ACSBTC_S2WERRNOSTRPTR 18
#define ACSBTC_ERRNOBYTEPTR 21
#define ACSBTC_ERRNOWORDPTR 22
#define ACSBTC_ERRNOLONGPTR 24
#define ACSBTC_HERRNOLONGPTR 25
#define ACSBTC_NUM_PACKET_FILTER_CHANNELS 40
#define ACSBTC_HAVE_ROUTING_API 41
#define ACSBTC_HAVE_INTERFACE_API 47
#define ACSBTC_HAVE_STATUS_API 53
#define ACSBTC_HAVE_DNS_API 54
#endif
